config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :companies
  resources :individuals
  resource :home
  root 'home#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  include GlobalID::Identification
  has_many :tasks, as: :client
end

app/models/individual.rb
class Individual < ActiveRecord::Base
  include GlobalID::Identification
  has_many :tasks, as: :client
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :client, polymorphic: true

  def global_client
    self.client.to_global_id if self.client.present?
  end

  def global_client=(client)
    self.client = GlobalID::Locator.locate client
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      redirect_to companies_path
    else
      render 'new'
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    @company.update_attributes(company_params)
    if @company.save
      redirect_to companies_path
    else
      render 'edit'
    end
  end

  def destroy
    Company.find(params[:id]).destroy
    redirect_to companies_path
  end

  private
  def company_params
    params.require(:company).permit(:name)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/individuals_controller.rb
class IndividualsController < ApplicationController
  def index
    @individuals = Individual.all
  end

  def new
    @individual = Individual.new
  end

  def create
    @individual = Individual.new(individual_params)
    if @individual.save
      redirect_to individuals_path
    else
      render 'new'
    end
  end

  def edit
    @individual = Individual.find(params[:id])
  end

  def update
    @individual = Individual.find(params[:id])
    @individual.update_attributes(individual_params)
    if @individual.save
      redirect_to individuals_path
    else
      render 'edit'
    end
  end

  def destroy
    Individual.find(params[:id]).destroy
    redirect_to individuals_path
  end

  private
  def individual_params
    params.require(:individual).permit(:name)
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
    @c = Company.all
    @i = Individual.all
  end

  def create
    p params
    p task_params
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path
    else
      render 'new'
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update_attributes(task_params)
    if @task.save
      redirect_to tasks_path
    else
      render 'edit'
    end
  end

  def destroy
    Task.find(params[:id]).destroy
    redirect_to tasks_path
  end

  private
  def task_params
    params.require(:task).permit(:name, :global_client)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/individuals_helper.rb
module IndividualsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/companies/_form.html.haml
= simple_form_for @company, html: { class: 'form-horizontal'} do |f|
  .fields
    .container
      .row
        .col-md-2
          = f.input :name
          %br
          = f.button :submit, class: 'btn btn-primary'

app/views/companies/edit.html.haml
= render 'form'

app/views/companies/index.html.haml
%table.table.table-bordered
  %th Name
  - @companies.each do |f|
    %tr
      %td= f.name
      %td
        = link_to "Edit", edit_company_path(f), class: 'btn btn-primary'
        = link_to 'Delete', company_path(f), method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure?' }
= link_to "New Company", new_company_path, class: 'btn btn-primary'
= link_to ' Home', root_path, class: 'btn btn-primary glyphicon glyphicon-home'

app/views/companies/new.html.haml
= render 'form'

app/views/home/index.html.haml
= link_to 'Companies', companies_path, class: 'btn btn-primary'
= link_to 'Individuals', individuals_path, class: 'btn btn-primary'
= link_to 'Tasks', tasks_path, class: 'btn btn-primary'

app/views/individuals/_form.html.haml
= simple_form_for @individual, html: { class: 'form-horizontal'} do |f|
  .fields
    .container
      .row
        .col-md-2
          = f.input :name
          %br
          = f.button :submit, class: 'btn btn-primary'

app/views/individuals/edit.html.haml
= render 'form'

app/views/individuals/index.html.haml
%table.table.table-bordered
  %th Name
  - @individuals.each do |f|
    %tr
      %td= f.name
      %td
        = link_to "Edit", edit_individual_path(f), class: 'btn btn-primary'
        = link_to 'Delete', individual_path(f), method: :delete, class: 'btn btn-danger', data: {confirm:'Are you sure?'}
= link_to "New Individual", new_individual_path, class: 'btn btn-primary'
= link_to ' Home', root_path, class: 'btn btn-primary glyphicon glyphicon-home'

app/views/individuals/new.html.haml
= render 'form'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title GlobalidPolymorphic
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      .row
        = yield

app/views/tasks/_form.html.haml
= simple_form_for @task, html: { class: 'form-horizontal'} do |f|
  .fields
    .container
      .row
        .col-md-2
          = f.input :name
          = f.grouped_collection_select :global_client, [ Company, Individual], :all, :model_name, :to_global_id, :name
          %br
          %br
          = f.button :submit, class: 'btn btn-primary'

app/views/tasks/edit.html.haml
= render 'form'

app/views/tasks/index.html.haml
.col-md-6
  %table.table.table-bordered
    %th Name
    %th Client Type
    %th Actions
    - @tasks.each do |f|
      %tr
        %td= f.name
        %td= f.client_type
        %td
          = link_to "Edit", edit_task_path(f), class: 'btn btn-primary'
          = link_to 'Delete', task_path(f), method: :delete, class: 'btn btn-danger', data: {confirm: "Are you sure?"}
        -#, data: {'Do you want to delete task?'}
  = link_to " New Task", new_task_path, class: 'btn btn-primary glyphicon glyphicon-plus'
  = link_to ' Home', root_path, class: 'btn btn-primary glyphicon glyphicon-home'

app/views/tasks/new.html.haml
New Task
= render 'form'